import type { NextPage } from 'next';
import Head from 'next/head';
import style from '../styles/Home.module.css';
import Search from '../components/search';

const Home: NextPage = () => {
	return (
		<div className={`container ${style.container}`}> 
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Search />
		</div>
	);
};

export default Home;
