import { useRouter } from 'next/router';
import type { NextPage } from 'next';
import style from '../styles/Home.module.css';
import Head from 'next/head';
import useSWR from 'swr';
import Search from '../components/search';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Preview: NextPage = () => {
    const router = useRouter()
    const { host, bedrock } = router.query

    const { data, error } = useSWR(`/api/server?host=${host ?? undefined}&bedrock=${bedrock ?? undefined}`, fetcher)

    return (
		<div className={`container ${style.container}`}> 
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Search value={`${host || ''}`} />

            {data ? data.message.ip : 'Loading...'}
		</div>
    )
}

export default Preview;