import { useRouter } from 'next/router';
import type { NextPage } from 'next';
import style from '../styles/Home.module.css';
import Head from 'next/head';
import useSWR from 'swr';
import Search from '../components/search';
import { Table } from 'react-bootstrap';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Preview: NextPage = () => {
    const router = useRouter()
    const { host, bedrock } = router.query

    const { data, error } = useSWR(`/api/server?host=${host ?? undefined}&bedrock=${bedrock ?? undefined}`, fetcher)

    return (
		<div className={`container ${style.container}`}> 
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Search value={`${host || ''}`} />

            <Table borderless>
                <tbody>
                    <tr>
                        <td>
                            <b>
                                IP
                            </b>
                        </td>

                        <td>{ data ? `${data.message.ip}` : 'Loading' }</td>
                    </tr>
                    <tr>
                        <td>
                            <b>
                                Edition
                            </b>
                        </td>

                        <td>{ data?.message?.edition ? `${data.message.edition.chatAt(0) + data.message.edition.slice(1).toLowerCase()}` : 'Loading' }</td>
                    </tr>
                    <tr>
                        <td>
                            <b>
                                Players
                            </b>
                        </td>

                        <td>{ data ? `${data.message.playersOnline}/${data.message.playersMax}` : 'Loading' }</td>
                    </tr>
                    <tr>
                        <td>
                            <b>
                                Version Name
                            </b>
                        </td>

                        <td>{ data ? `${data.message.versionName}` : 'Loading' }</td>
                    </tr>
                    <tr>
                        <td>
                            <b>
                                Version Protocol
                            </b>
                        </td>

                        <td>{ data ? `${data.message.versionProtocol}` : 'Loading' }</td>
                    </tr>
                    <tr>
                        <td>
                            <b>
                                Motd
                            </b>
                        </td>

                        <td>{ data ? `${data.message.motd.html}` : 'Loading' }</td>
                    </tr>
                </tbody>
            </Table>

            {data ? data.message.ip : 'Loading...'}
		</div>
    )
}

export default Preview;